server:
  port: 8080

zuul:
  routes:
    todos:
      path: /api/todos/**
      strip-prefix: false
      service-id: todo-service
    proxy:
      path: /proxy/**
      strip-prefix: true
      service-id: proxy-service
  strip-prefix: false

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    registry-fetch-interval-seconds: 5
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: warn
    com.melardev: trace
    org.springframework.cloud.netflix.zuul: info
